sequence_length: 500
train_stride: 250
eval_stride: 500
normalize: false

model_type: bilstm
bilstm:
  hidden_size: 256
  num_layers: 2
  dropout: 0.3

epochs: 50
batch_size: 32
lr: 0.001
scheduler: cosine
imbalance_strategy: batched_oversample
undersample_ratio: 3
use_class_weights: false