sequence_length: 50
train_stride: 25
eval_stride: 50
normalize: false

model_type: bilstm
bilstm:
  hidden_size: 256
  num_layers: 2
  dropout: 0.3

epochs: 50
batch_size: 32
lr: 1e-3
scheduler: cosine
imbalance_strategy: batched_oversample
undersample_ratio: 3
use_class_weights: false